POST  http://localhost:8989/user/getUser
Accept: application/json
Content-Type: application/json

{
  "order": {
    "id": 102,
    "name": "book1",
    "qty": 13,
    "price": 1000
  },
  "payment": {}
}

###

GET http://localhost:8989/laboratory/room
Accept: application/json
Content-Type: application/json

###

###

DELETE http://localhost:8200/laboratory/room/1
Accept: application/json
Content-Type: application/json

###

###

POST http://localhost:8200/laboratory/room
Accept: application/json
Content-Type: application/json

{
  "floor": 2,
  "roomSupervisor": "NowakJan"
}

###



PUT http://localhost:8200/laboratory/room/2
Accept: application/json
Content-Type: application/json

{
  "floor": 3,
  "roomSupervisor": "NOWY+UP"
}

###

POST  http://localhost:8200/laboratory/desk
Accept: application/json
Content-Type: application/json

{
  "deskType": "NORMAL",
  "roomId": 2
}

###

PUT  http://localhost:8200/laboratory/desk/4
Accept: application/json
Content-Type: application/json

{
  "deskType": "NORMAL",
  "roomId": 1
}

###

DELETE  http://localhost:8200/laboratory/desk/4
Accept: application/json
Content-Type: application/json


###

GET  http://localhost:8200/laboratory/computer
Accept: application/json
Content-Type: application/json

###

GET  http://localhost:8200/laboratory/computer/2
Accept: application/json
Content-Type: application/json

###

GET  http://localhost:8200/laboratory/computer/desk/4
Accept: application/json
Content-Type: application/json

###

POST  http://localhost:8200/laboratory/computer
Accept: application/json
Content-Type: application/json

{
  "monitors": 2,
  "headphones": true,
  "microphone": true,
  "operatingSystem": "windows",
  "graphicCard": "2gb",
  "cpu": "INTEL",
  "ram": 2,
  "drive": 512,
  "networkType": "WIFI",
  "deskId": 4
}

###

PUT  http://localhost:8200/laboratory/computer/2
Accept: application/json
Content-Type: application/json

{
  "monitors": 1,
  "headphones": true,
  "microphone": true,
  "operatingSystem": "Linux",
  "graphicCard": "3gb",
  "cpu": "AMD",
  "ram": 2,
  "drive": 512,
  "networkType": "WIFI",
  "deskId": 4
}

###

DELETE  http://localhost:8200/laboratory/computer/1
Accept: application/json
Content-Type: application/json


###

POST  http://localhost:8989/user/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


###

GET  http://localhost:8989/user/new
Accept: application/json
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiIxIiwicm9sZSI6IlJPTEVfVVNFUiJ9.R7_p06Ptjf7FfgQMtSZgQvOJ81AH2o876N4xgEYCYG6OEzyq4bMuPCUr8dv-3D5knN1TRBS2VcZkx9VuszvUJg
