POST  http://localhost:8989/user/getUser
Accept: application/json
Content-Type: application/json

{
  "order": {
    "id": 102,
    "name": "book1",
    "qty": 13,
    "price": 1000
  },
  "payment": {}
}

###

GET http://localhost:8989/user/getUser
Accept: application/json
Content-Type: application/json

###