server:
  port: 8000
spring:
  datasource:
    username: root
    password: Passw0rd2
    url: jdbc:mysql://localhost:3306/user_service?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: USER-SERVICE